[package]
name = "telemetry"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
sts_lib = { path = "../../lib" }
tokio = { version = "1.43.0", features = [
    "full",
    "net",
    "rt-multi-thread",
    "windows-sys",
] }
