[package]
name = "sim"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
bitflags = "2.6.0"
once_cell = "1.20.2"

[dev-dependencies]
base64 = "0.22.1"
itertools = "0.14.0"
pretty_assertions = "1.4.1"
